### ISSUE TITLE
TypeError: 'dict_keys' object is not subscriptable

### ISSUE THREAD

**Issue by iguanaman** [artyfacialintelagent/CloneCleaner#2]
Hi, great idea but I get an error on load;
```
Error calling: D:\Work\github\AUTOMATIC1111\stable-diffusion-webui\extensions\CloneCleaner\scripts\clonecleaner.py/ui
Traceback (most recent call last):
  File "D:\Work\github\AUTOMATIC1111\stable-diffusion-webui\modules\scripts.py", line 270, in wrap_call
    res = func(*args, **kwargs)
  File "D:\Work\github\AUTOMATIC1111\stable-diffusion-webui\extensions\CloneCleaner\scripts\clonecleaner.py", line 76, in ui
    exclude_regions = gr.Dropdown(choices=regions, label="Exclude regions", multiselect=True)
  File "D:\Work\github\AUTOMATIC1111\stable-diffusion-webui\venv\lib\site-packages\gradio\components.py", line 1306, in __init__
    self.test_input = self.choices[0] if len(self.choices) else None
TypeError: 'dict_keys' object is not subscriptable
```

And this error when generating;
```
Error running process: D:\Work\github\AUTOMATIC1111\stable-diffusion-webui\extensions\CloneCleaner\scripts\clonecleaner.py
Traceback (most recent call last):
  File "D:\Work\github\AUTOMATIC1111\stable-diffusion-webui\modules\scripts.py", line 417, in process
    script.process(p, *script_args)
TypeError: CloneCleanerScript.process() missing 10 required positional arguments: 'is_enabled', 'gender', 'insert_start', 'declone_weight', 'use_main_seed', 'declone_seed', 'use_components', 'exclude_regions', 'exclude_hairlength', and 'exclude_haircolor'
```

Python 3.10.9

**Comment by artyfacialintelagent** [comment]
I can't reproduce this on my system but the error message gave me a hint as to what the problem may be. Could you please checkout the branch `experimental-fix-issue-2` and see if that helps? Either go to the extension folder and do `git checkout experimental-fix-issue-2`, or reinstall the extension and enter that branch name in the box under the github url.

**Comment by iguanaman** [comment]
Thanks, yup that worked 

BTW I had to do `git fetch --all` first, just FYI in case you ask someone else to do similar

**Comment by artyfacialintelagent** [comment]
Glad it worked! The fix is now in the 'dev' branch which will get other pre-release changes and bugfixes, and it will appear in 'main' when I release v1.0 in a week or two (if all goes well).
